default_context:
  project_name: 'utterance_organizer'
  project_slug: 'utterance_organizer'
  domain_main: 'utterance_organizer.com'
  domain_staging: 'stag.utterance_organizer.com'
  docker_swarm_stack_name_main: 'utterance_organizer-com'
  docker_swarm_stack_name_staging: 'stag-utterance_organizer-com'
  secret_key: '110d177fe2b7913d26c0d86566535ddba7e41882854c3a78d0cd3c65b7937777'
  first_superuser: 'brunoyui@gmail.com'
  first_superuser_password: '65df0418448627f388890d305913ef00e689f9ddccdba5a2515d5eee1daaf7ce'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.utterance_organizer.com", "https://stag.utterance_organizer.com", "https://utterance_organizer.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'brunoyui@gmail.com'
  postgres_password: 'sinofilus'
  pgadmin_default_user: '[3~'
  pgadmin_default_user_password: '65df0418448627f388890d305913ef00e689f9ddccdba5a2515d5eee1daaf7ce'
  traefik_constraint_tag: 'utterance_organizer.com'
  traefik_constraint_tag_staging: 'stag.utterance_organizer.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:65df0418448627f388890d305913ef00e689f9ddccdba5a2515d5eee1daaf7ce'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
